# ============================================================
# POC 46 Creator Distribution Funnel — Multi-Stage Dockerfile
# Services: Next.js Frontend (port 3000) + FastAPI Backend (port 5000)
# ============================================================

# ─────────────────────────────────────────────────────────────
# STAGE 1 — frontend-deps
# Install Node dependencies (cached layer, only rebuilt on lockfile change)
# ─────────────────────────────────────────────────────────────
FROM node:20-alpine AS frontend-deps
RUN apk add --no-cache libc6-compat
WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci

# ─────────────────────────────────────────────────────────────
# STAGE 2 — frontend-builder
# Compile Next.js production assets with build-time env injection.
# NEXT_PUBLIC_* variables are baked into the static bundle at build time.
# ─────────────────────────────────────────────────────────────
FROM node:20-alpine AS frontend-builder
WORKDIR /app/frontend

COPY --from=frontend-deps /app/frontend/node_modules ./node_modules
COPY frontend/ .

# Accept build-time variables from docker-compose args
ARG NEXT_PUBLIC_API_URL=http://localhost:5000
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=

ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=$NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# ─────────────────────────────────────────────────────────────
# STAGE 3 — frontend-runner
# Minimal production image using Next.js standalone output.
# Runs as a non-root system user for security.
# ─────────────────────────────────────────────────────────────
FROM node:20-alpine AS frontend-runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Create a locked-down system user
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy standalone output and static assets from builder
COPY --from=frontend-builder /app/frontend/public                        ./public
COPY --from=frontend-builder --chown=nextjs:nodejs /app/frontend/.next/standalone ./
COPY --from=frontend-builder --chown=nextjs:nodejs /app/frontend/.next/static     ./.next/static

USER nextjs
EXPOSE 3000

# server.js is generated by Next.js standalone output
CMD ["node", "server.js"]

# ─────────────────────────────────────────────────────────────
# STAGE 4 — backend-runner
# FastAPI served via Uvicorn. Runs as a slim Python 3.12 image.
# ─────────────────────────────────────────────────────────────
FROM python:3.12-slim AS backend-runner
WORKDIR /app/backend

# Suppress .pyc files and force unbuffered logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies first (cached layer)
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend application
COPY backend/ .

EXPOSE 5000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
