# ============================================================
# Cinematic Rail PoC — Multi-Stage Dockerfile
#
# Stages:
#   1. frontend-deps     — install Node deps (cache layer)
#   2. frontend-builder  — compile Next.js standalone bundle
#   3. frontend-runner   — minimal production image (non-root)
#   4. backend-runner    — FastAPI via Uvicorn (non-root)
#
# Build-time env vars (NEXT_PUBLIC_*) are injected via
# docker-compose build args and baked into the JS bundle.
# Runtime secrets (DATA_API_KEY) come in via env_file at
# container start — they are never baked into the image.
# ============================================================


# ─────────────────────────────────────────────────────────────
# STAGE 1 — frontend-deps
# Only copies lockfiles so this layer is re-used on every build
# unless package.json / package-lock.json actually changes.
# ─────────────────────────────────────────────────────────────
FROM node:22-alpine AS frontend-deps

# libc6-compat is needed for some native Node add-ons on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app/frontend

# Copy manifests first — maximises Docker cache hit rate
COPY frontend/package.json frontend/package-lock.json* ./

# Clean install (respects lockfile exactly, no hoisting surprises)
RUN npm ci --prefer-offline


# ─────────────────────────────────────────────────────────────
# STAGE 2 — frontend-builder
# Accepts NEXT_PUBLIC_* at build time so they get baked into
# the static bundle.  Never pass secrets here.
# ─────────────────────────────────────────────────────────────
FROM node:22-alpine AS frontend-builder

WORKDIR /app/frontend

# Pull pre-installed node_modules from the deps stage
COPY --from=frontend-deps /app/frontend/node_modules ./node_modules

# Copy the full frontend source
COPY frontend/ .

# ── Build-time arguments ──────────────────────────────────────
# Passed in by docker-compose via the `build.args` block.
# Keep defaults empty so the build fails loud if you forget them
# rather than silently shipping placeholder strings.
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN

# Promote ARGs to ENVs so Next.js picks them up during `next build`
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}

# Opt-out of Next.js anonymous telemetry
ENV NEXT_TELEMETRY_DISABLED=1

# next.config.ts has output: 'standalone' — this produces a
# self-contained server.js plus a pruned node_modules copy.
RUN npm run build


# ─────────────────────────────────────────────────────────────
# STAGE 3 — frontend-runner
# Lean production image — only the standalone output lands here.
# Runs as a non-root user to limit blast radius if exploited.
# ─────────────────────────────────────────────────────────────
FROM node:22-alpine AS frontend-runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
# Bind to all interfaces inside the container
ENV HOSTNAME=0.0.0.0

# Least-privilege system account
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 --ingroup nodejs nextjs

# ── Copy only what Next.js standalone needs ───────────────────
# public/ — static assets served directly
COPY --from=frontend-builder /app/frontend/public ./public

# standalone/ — trimmed server.js + minimal node_modules
COPY --from=frontend-builder --chown=nextjs:nodejs \
     /app/frontend/.next/standalone ./

# .next/static — hashed CSS/JS chunks referenced by the HTML
COPY --from=frontend-builder --chown=nextjs:nodejs \
     /app/frontend/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# server.js is generated by `next build` when output:'standalone'
CMD ["node", "server.js"]


# ─────────────────────────────────────────────────────────────
# STAGE 4 — backend-runner
# Slim Python 3.12 image serving FastAPI via Uvicorn.
# Runtime secrets are injected via env_file — nothing sensitive
# is written into this image layer.
# ─────────────────────────────────────────────────────────────
FROM python:3.12-slim AS backend-runner

WORKDIR /app/backend

# Suppress .pyc files (keeps image clean) and force unbuffered
# stdout/stderr so log lines appear immediately in `docker logs`.
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Least-privilege system account
RUN addgroup --system --gid 1001 appgroup \
 && adduser  --system --uid 1001 --ingroup appgroup appuser

# ── Install Python dependencies ───────────────────────────────
# Copy requirements first — cached unless requirements.txt changes
COPY backend/requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

# Copy application source (CSV data file + main.py)
COPY backend/ .

# Fix ownership before dropping privileges
RUN chown -R appuser:appgroup /app/backend

USER appuser

EXPOSE 5000

# Run with a single worker for the PoC.
# For production scale-out, set --workers to match CPU count or
# use Gunicorn with the Uvicorn worker class instead.
CMD ["uvicorn", "main:app", \
     "--host", "0.0.0.0", \
     "--port", "5000", \
     "--workers", "1", \
     "--no-access-log"]
